# Get all customers
GET http://127.0.0.1:5000/api/users/customers
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1MjA5NTc4OSwianRpIjoiMzE5YzkyY2UtY2YyMi00Nzg0LWE0M2QtMTBlYzg5ZjZiZjhjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzUyMDk1Nzg5LCJjc3JmIjoiYmM2YThhMzUtMjk1Mi00Njc5LTkyZjEtM2VjMmQyNzY3NTJkIiwiZXhwIjoxNzUyMDk2Njg5fQ.F2wQD_Bwt8fxGQTwFuMD8tCbt21e9cz6Q6nOxk_0Nus"
Accept: application/json