"""Added foreign key to payments

Revision ID: 287b283684c1
Revises: 6b2cee1ba5fb
Create Date: 2025-07-09 18:04:07.781089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '287b283684c1'
down_revision = '6b2cee1ba5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('booking_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('booking_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('price_per_hour',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('availability_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint(None, ['service_name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=10), nullable=False))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('password')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('availability_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('price_per_hour',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('service_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('booking_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('booking_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
