"""Booking start and end time is not unique

Revision ID: 2ea7f4a9a7ed
Revises: e36a47fe1357
Create Date: 2025-07-14 17:40:55.624214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea7f4a9a7ed'
down_revision = 'e36a47fe1357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('end_time'))
        batch_op.drop_index(batch_op.f('start_time'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('start_time'), ['start_time'], unique=True)
        batch_op.create_index(batch_op.f('end_time'), ['end_time'], unique=True)

    # ### end Alembic commands ###
